-- Math Symbols Dictionary

_MATH_TABLE = {
  -- Basic Math Sumbols
  ['dengyu'] = {"=","≡"},
  ['budengyu'] = {"≠"},
  ['yuedengyu'] = {"≈"},
  ['dayu'] = {">"},
  ['xiaoyu'] = {"<"},
  ['dayudengyu'] = {"≥"},
  ['jiajian'] = {"±"},
  ['cheng'] = {"×","*","⋅"},
  ['chu'] = {"÷","/"},
  ['mod'] = {"mod"},
  ['dian'] = {"."},
  ['genhao'] = {"√"},
  ['baifen'] = {"%"},
  ['qianfen'] = {"‰"},
  ['baiwanfen'] = {"ppm"},
  ['shiyifen'] = {"ppb"},
  ['wanyifen'] = {"ppt"},
  -- Geometry Symbols
  ['jiao'] = {"∠"},
  ['zhijiao'] = {"∟"},
  ['du'] = {"°","deg"},
  ['fen'] = {"′"},
  ['miao'] = {"″"},
  ['chuizhi'] = {"⊥"},
  ['pingxing'] = {"∥"},
  ['quandeng'] = {"≅"},
  ['xiangsi'] = {"~"},
  ['sanjiaoxing'] = {"Δ"},
  ['hudu'] = {"c","rad"},
  ['tidu'] = {"g","grad"},
  -- Algebra symbols
  ['weizhishu'] = {"x"},
  ['dingyixiangdeng'] = {"≜",":="},
  ['jinsi'] = {"~"},
  ['zhengbiyu'] = {"∝"},
  ['wuxian'] = {"∞"},
  ['yuanxiaoyu'] = {"≪"},
  ['yuandayu'] = {"≫"},
  ['xiangxiaquzheng'] = {"⌊⌋"},
  ['xiangshangquzheng'] = {"⌈⌉"},
  ['jiecheng'] = {"!"},
  ['jueduizhi'] = {"||"},
  ['fuhe'] = {"∘"},
  -- Linear Algebra Symbols
  ['emitejuzhen'] = {"^†","^*"},
  ['zhi'] = {"rank()"},
  ['wei'] = {"dim()"},
  -- Set Theory
  ['jiao'] = {"∩"},
  ['bing'] = {"∪"},
  ['baohanyu'] = {"⊆"},
  ['zhenbaohanyu'] = {"⊂"},
  ['bubaohanyu'] = {"⊄"},
  ['baohan'] = {"⊇"},
  ['zhenbaohan'] = {"⊃"},
  ['bubaohan'] = {"⊅"},
  ['buji'] = {"^c"},
  ['chaji'] = {"\\","-"},
  ['duichencha'] = {"∆","⊖"},
  ['shuyu'] = {"∈"},
  ['bushuyu'] = {"∉"},
  ['dikaerji'] = {"×"},
  ['kongji'] = {"Ø"},
  ['shishu'] = {"ℝ"},
  ['zhengshu'] = {"ℤ"},
  ['ziranshu'] = {"ℕ"},
  ['youlishu'] = {"ℚ"},
  ['fushu'] = {"ℂ"},
  ['quanji'] = {"𝕌"},
  -- Logic Symbols
  ['he'] = {"∧","&"},
  ['huo'] = {"∨","|"},
  ['fei'] = {"'","¬","!","~"},
  ['yihuo'] = {"⊕"},
  ['yunhan'] = {"⇒"},
  ['dengjia'] = {"⇔","↔"},
  ['suoyou'] = {"∀"},
  ['cunzai'] = {"∃"},
  ['bucunzai'] = {"∄"},
  ['yinwei'] = {"∵"},
  ['suoyi'] = {"∴"},
  -- Caculus & Analysis symbols
  ['jifen'] = {"∫"},
  ['fai'] = {"∮","∯","∰"},
  ['nabla'] = {"∇"},
  -- Greek Alphabet
  ['aerfa'] = {"Α","α"},
  ['beita'] = {"Β","β"},
  ['gama'] = {"Γ","γ"},
  ['deerta'] = {"Δ","δ"},
  ['yipuxilong'] = {"Ε","ε"},
  ['zeta'] = {"Ζ","ζ"},
  ['yita'] = {"Η","η"},
  ['xita'] = {"Θ","θ"},
  ['yueta'] = {"Ι","ι"},
  ['aiouta'] = {"Ι","ι"},
  ['kapa'] = {"Κ","κ"},
  ['lamuda'] = {"Λ","λ"},
  ['miu'] = {"Μ","μ"},
  ['miou'] = {"Μ","μ"},
  ['niu'] = {"Ν","ν"},
  ['kexi'] = {"Ξ","ξ"},
  ['oumikelong'] = {"Ο","ο"},
  ['aomikerong'] = {"Ο","ο"},
  ['pai'] = {"∏","Π","π"},
  ['rou'] = {"Ρ","ρ"},
  ['xigema'] = {"∑","Σ","σ"},
  ['tao'] = {"Τ","τ"},
  ['yupuxilong'] = {"Υ","υ"},
  ['fuai'] = {"Φ","φ"},
  ['kai'] = {"Χ","χ"},
  ['pusai'] = {"Ψ","ψ"},
  ['aomijia'] = {"Ω","ω"},
  ['alpha'] = {"Α","α"},
  ['beta'] = {"Β","β"},
  ['gamma'] = {"Γ","γ"},
  ['delta'] = {"Δ","δ"},
  ['epsilon'] = {"Ε","ε"},
  ['zeta'] = {"Ζ","ζ"},
  ['eta'] = {"Η","η"},
  ['theta'] = {"Θ","θ"},
  ['iota'] = {"Ι","ι"},
  ['kappa'] = {"Κ","κ"},
  ['lambda'] = {"Λ","λ"},
  ['mu'] = {"Μ","μ"},
  ['nu'] = {"Ν","ν"},
  ['xi'] = {"Ξ","ξ"},
  ['omicron'] = {"Ο","ο"},
  ['pi'] = {"∏","Π","π"},
  ['rho'] = {"Ρ","ρ"},
  ['sigma'] = {"∑","Σ","σ"},
  ['tau'] = {"Τ","τ"},
  ['upsilon'] = {"Υ","υ"},
  ['phi'] = {"Φ","φ"},
  ['chi'] = {"Χ","χ"},
  ['psi'] = {"Ψ","ψ"},
  ['omega'] = {"Ω","ω"},
}

function getMathTablePhrase(input)
  local ret
  ret = _MATH_TABLE[input]
  return ret
end

ime.register_trigger("getMathTablePhrase", "常用数学符号", {'*'}, {})